# Generated by Django 5.2 on 2025-05-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(choices=[('aditivo', 'Aditivo'), ('aqua', 'Aqua'), ('aves', 'Aves'), ('pet', 'Pet'), ('ruminantes', 'Ruminantes'), ('suinos', 'Suínos'), ('revenda', 'Revenda')], max_length=50)),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_date', models.DateField()),
                ('payment_due_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.user')),
            ],
        ),
    ]
