# Generated by Django 5.2 on 2025-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
